TabloidCLI/.vscode/launch.json
TabloidCLI/.vscode/tasks.json
TabloidCLI/Program.cs

added a console message to welcome the user when the program starts

program now welcomes the user

---

TabloidCLI/Models/Journal.cs
TabloidCLI/Program.cs
TabloidCLI/Repositories/BlogRepository.cs
TabloidCLI/Repositories/JournalRepository.cs
TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/BlogManager.cs
TabloidCLI/UserInterfaceManagers/JournalManager.cs
TabloidCLI/UserInterfaceManagers/MainMenuManager.cs
TabloidCLI/UserInterfaceManagers/PostManager.cs

Completed number 2, where we created the menu's.

Nt initial

---

.vscode/launch.json
.vscode/tasks.json
TabloidCLI/Models/Journal.cs
TabloidCLI/Repositories/JournalRepository.cs
TabloidCLI/UserInterfaceManagers/JournalManager.cs

allows user to add journal entry to database

---

TabloidCLI/Repositories/BlogRepository.cs
TabloidCLI/UserInterfaceManagers/BlogManager.cs

Finished the "Add Blog" piece within the BlogManager and the "Insert Blog" piece within the BlogRepository.

finished add blog

---

TabloidCLI/Repositories/JournalRepository.cs
TabloidCLI/UserInterfaceManagers/JournalManager.cs

Allows user to see a list of all journal entries from the journal manager view.

Wm list journals

---

TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/PostManager.cs

users can see a list of all posts from the post management menu

post list added

---

TabloidCLI/Repositories/TagRepository.cs

made the add function for tags and works.

can now add new tags

---

TabloidCLI/Repositories/TagRepository.cs
TabloidCLI/UserInterfaceManagers/AuthorDetailManager.cs
TabloidCLI/UserInterfaceManagers/AuthorManager.cs
TabloidCLI/UserInterfaceManagers/TagManager.cs

put in function to edit tags
changed files, tagRepo, tagManager
on branch dc-taggs
test it by going to tags management and go to edit

edit to tags

---

TabloidCLI/Repositories/BlogRepository.cs
TabloidCLI/UserInterfaceManagers/BlogManager.cs

1) Task: Completed the RemoveBlog and EditBlog methods on the BlogManager, and the Delete and Update methods in the Blog Repository. 
2) Files Changes: BlogManager, BlogRepository.
3) Branch = NT-RemoveBlog

Nt remove blog

---

TabloidCLI/Repositories/JournalRepository.cs
TabloidCLI/UserInterfaceManagers/JournalManager.cs

- Allows the user to delete a journal entry.
- Completes Get and Delete Methods in Journal Repository.
- Branch: wm-deleteJournalEntry
- Files Changed: JournalManger.cs, JournalRepository.cs
- Test: From main menu select "1", From Journal Menu select "5", Provide Id of journal you wish to delete

Wm delete journal entry

---

TabloidCLI/Program.cs
TabloidCLI/UserInterfaceManagers/JournalManager.cs
TabloidCLI/UserInterfaceManagers/MainMenuManager.cs

- Allows the user to pick a background color upon application launch.
- Branch: wm-appBackgroundColor
- Files Changed: Program.cs
- Test: Launch the console application, select number of color you'd like you're background to be.

WM app background color

---

TabloidCLI/Repositories/BlogRepository.cs
TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/AuthorManager.cs
TabloidCLI/UserInterfaceManagers/PostManager.cs

On branch lj-addPost 
fetch and checkout to branch
select option for post management and then the option for add post
files edited: PostManager.cs, PostRepository.cs

Lj add post

---

TabloidCLI/Repositories/BlogRepository.cs
TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/BlogDetailManager.cs
TabloidCLI/UserInterfaceManagers/BlogManager.cs

Finished the ViewBlogTags method in the BlogDetailManager.

Nt view blog tags

---

TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/PostManager.cs

on branch lj-editPost
fetch and check out to branch
-choose post management option in main menu
-choose edit post option
-edit post
-choose list post option to make sure edits have been saved
files edited: PostManager.cs, PostRepository.cs

Lj edit post

---

TabloidCLI/Repositories/TagRepository.cs
TabloidCLI/UserInterfaceManagers/SearchManager.cs

tagRepo, searchManager
dc-notes
search by tagName in blogs and posts in search manager

search for blogs and posts

---

TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/PostManager.cs

on branch lj-deletePost  
fetch and check out to branch  
-choose post management option in main menu  
-create a new post  
-delete new post
-choose list post option to make sure post was deleted
files edited: PostManager.cs, PostRepository.cs

Lj delete post

---

TabloidCLI/.vscode/settings.json
TabloidCLI/Repositories/TagRepository.cs

tagRepo
reformatted for merging
dc-tagRepo

Reformat tagRepo

---

TabloidCLI/Models/Note.cs
TabloidCLI/Repositories/NoteRepository.cs
TabloidCLI/UserInterfaceManagers/NoteManager.cs
TabloidCLI/UserInterfaceManagers/PostDetailsManager.cs

- Allows the user to navigate to Note Management menu from Post Details Menu. 
- Branch: wm-noteManagement
- Files Changed: PostDetails.cs
- Files Created: Note.cs, NoteManager.cs, NoteRepository.cs
- Test: Launch the console application, navigate to view post, navigate to post details, navigate to note management

WM note management

---

TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/PostDetailsManager.cs

on branch lj-addTagToPost
fetch and check out to branch
-choose post management option in main menu
-choose post details
-choose add tag
-look for success message
files edited: PostRepository.cs, PostDetailsManager.cs

Lj add tag to post

---

TabloidCLI/UserInterfaceManagers/SearchManager.cs

SearchManager
dc-searchAll
added search all function to search manager that just uses the blog/post/author search functions all at once

search all function

---

TabloidCLI/Repositories/NoteRepository.cs
TabloidCLI/UserInterfaceManagers/BlogManager.cs
TabloidCLI/UserInterfaceManagers/JournalManager.cs
TabloidCLI/UserInterfaceManagers/NoteManager.cs
TabloidCLI/UserInterfaceManagers/PostManager.cs

Task Completed: Added the AddNote Method in NoteManager, and added the associated Insert Method in the NoteRepository. 
BranchName = NT-AddNote.
Files Changed = NoteManager.cs, NoteRepository.cs.

Finished AddNote method for NoteManager

---

TabloidCLI/UserInterfaceManagers/PostDetailsManager.cs

Task Completed: Added the "ViewPostTags" data to the "View" option within the PostDetailsManager. 
Files Updated: PostDetailsManager. 
Branch Name: NT-ViewPostsTags

Nt view posts tags

---

TabloidCLI/Models/Post.cs
TabloidCLI/Repositories/PostRepository.cs
TabloidCLI/UserInterfaceManagers/PostDetailsManager.cs

on branch lj-removeTagFromPost  
fetch and check out to branch  
-choose post management option in main menu  
-choose post details  
-choose remove tag
-select tag to remove  
-look for success message
files edited: PostRepository.cs, PostDetailsManager.cs, Post.cs

Lj remove tag from post
